### PR TITLE
2.13 for real

### LINKED ISSUE #107: Release for 2.13

### PR DESCRIPTION
**Pull request by kubukoz**
TODO:

- [ ] Stable http4s with a dependency on CE 2.0.0 final (later)
- [x] ~Cogen derivation (coming soon to scalacheck-magnolia)~ manual Cogen instances where needed
- [x] Stable doobie
- [x] cats-tagless with a dependency on cats 2.0.0 final
- [x] check if microsite builds

For release notes:
- refined was removed in favor of a FiniteDuration in the doobie module
- mention changed signatures that used to take a semigroup instance

Closes #107

### CODE REVIEW

**Comment by CremboC** [comment]
I am very keen to try this library, but I need 2.13 support. Would it be possible to release a milestone release with this branch?

**Comment by kubukoz** [comment]
@CremboC definitely! It'll have to be with a milestone of http4s as well, though. I'll try to do it this week.

**Comment by CremboC** [comment]
Yup that's no problem for me, happy with a http4s milestone 👍

**Comment by kubukoz** [comment]
@CremboC I think it should work now (0.7.0-M1) :)

**Pull request merged**
