### PR TITLE
Update libs

### PR DESCRIPTION
**Pull request by amsayk**
I upgraded all libs in previous PR except c3. And I crossed compiled with Scala 3. Unfortunately Scala 2.12 can't work with this. So let's me know if we really need Scala 2.12.

I think this is good to go while we wait for doobie to go ce3.

### CODE REVIEW

**Comment by kubukoz** [comment]
This will definitely conflict with #228 ;)

I think we should just wait until everyone publishes for CE3 and we'll do all that there.

**Comment by amsayk** [comment]
Yes it will; Fair enough. I will keep a watch on this and we can continue later.

**Comment by kubukoz** [comment]
Are any libraries in this PR not covered by the other one? I thought I updated everything.

**Comment by amsayk** [comment]
No, you got everything. In terms of update, the big diff is I cross compiled with Scala 3 and drop 2.12.

Are we ok with dropping Scala 2.12 ?

**Comment by kubukoz** [comment]
ah, I didn't notice Scala 3. This isn't trivial because for some dependencies (e.g. cats, cats-effect) we'll want out see Scala 3-built artifacts, and for others (the ones that don't publish for 3.x specifically) we might have to use `withDottyCompat` (using 2.13 artifacts for the interop). I think it's too early to get into that territory, as I don't know e.g. Akka's plans for the upgrade.

I don't think it's the right moment to drop 2.12 yet either, it's probably the most popular Scala version currently used.

**Comment by amsayk** [comment]
Looks like upgrading SBT breaks Travis CI.

**Comment by amsayk** [comment]
OK cool. Then after moving to ce3, we will figure how to publish for Scala 2.12, 2.13 and Scala 3.

**Comment by kubukoz** [comment]
#296 sounds like a good thing to work on, I've slowly been moving all my builds to GH :)

it'll also help here hopefully

**Comment by kubukoz** [comment]
btw. thanks for the interest in helping with this project, I really appreciate it! Just keep in mind we're on the same page before putting any significant efforts to avoid conflicting changes like this one ;)

**Comment by amsayk** [comment]
I guess we can close this for now since all is in the ce3 pull request.

**Comment by kubukoz** [comment]
Yeah, sorry about that 😓

**Comment by kubukoz** [comment]
Now I'm thinking this was premature on my side, it might still take some time for doobie to release and it'd be nice to have a version before that.

If you're interested in reviving this (without the Scala 3 support though, first need to learn what Akka is planning), I'll happily accept that.

**Pull request closed without merging**
